name: Code Quality

on: [pull_request]

jobs:
  code_quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black pylint

    - name: Run Black
      run: black . --check

    - name: Run Flake8
      run: flake8 .

    - name: Run pylint
      run: |
        pylint **/*.py --fail-under=10 --disable=all --enable=missing-docstring

    - name: Reject PR if pylint check fails
      if: failure()
      run: exit 1
